[theme]
primaryColor="#29B5E8"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#D4F0FA"
textColor="#000000"
font="monospace"

[server]
port = 8501
enableStaticServing = true
sslCertFile = ''
sslKeyFile = ''
headless = true
enableXsrfProtection = false
enableCORS = false